# Generated by Django 4.2.10 on 2024-02-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProofOfConcept', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Squirrels',
            new_name='Squirrel',
        ),
    ]
