# Generated by Django 4.2.10 on 2024-02-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProofOfConcept', '0002_rename_squirrels_squirrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='image',
            field=models.ImageField(upload_to='ProofOfConcept/files/images'),
        ),
    ]
