# Generated by Django 4.2.10 on 2024-02-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProofOfConcept', '0003_alter_squirrel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
